# YOLOS 默认配置文件
# 这是系统的基础配置，其他环境配置会覆盖这些设置

# 应用基础信息
app:
  name: "YOLOS"
  version: "1.0.0"
  description: "You Only Look Once for Object Detection System"
  author: "YOLOS Team"
  environment: "${YOLOS_ENV:development}"  # 支持环境变量
  
# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console:
    enabled: true
    level: "INFO"
  file:
    enabled: true
    level: "DEBUG"
    path: "logs/yolos.log"
    max_size: "10MB"
    backup_count: 5
    rotation: "size"

# 调试配置
debug:
  enabled: false
  profiling: false
  memory_tracking: false
  performance_monitoring: false
  verbose_errors: false

# 服务器配置
server:
  host: "127.0.0.1"
  port: 8000
  debug: false
  auto_reload: false
  workers: 1
  timeout: 30

# 数据库配置
database:
  type: "sqlite"
  path: "data/yolos.db"
  pool_size: 10
  echo: false

# 缓存配置
cache:
  type: "memory"
  ttl: 3600
  max_size: 1000

# 模型配置
models:
  # 默认模型 - 升级到YOLOv11
  default_model: "yolov11s.pt"
  model_type: "yolov11"
  model_size: "s"
  cache_dir: "models"
  download_timeout: 300
  auto_download: true
  use_gpu: "auto"
  batch_size: 1
  precision: "fp16"
  
  # YOLOv11特定配置
  yolov11:
    # C2PSA模块配置
    c2psa:
      enabled: true
      attention_type: "pyramid_slice"
      multi_scale: true
    
    # C3k2模块配置  
    c3k2:
      enabled: true
      parallel_conv: true
      channel_separation: true
      kernel_sizes: [3, 5, 7]  # 多尺度卷积核
  
  # 推理配置
  inference:
    confidence_threshold: 0.25
    iou_threshold: 0.45
    max_detections: 1000
    tensorrt_optimize: true
    dynamic_batching: true
    
  # 预处理配置
  preprocessing:
    input_size: [640, 640]
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# 数据配置
data:
  dataset_dir: "datasets"
  image_formats: [".jpg", ".jpeg", ".png", ".bmp", ".tiff"]
  video_formats: [".mp4", ".avi", ".mov", ".mkv"]
  
  dataloader:
    num_workers: 4
    pin_memory: true
    drop_last: false

# 训练配置
training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  optimizer: "SGD"
  scheduler: "linear"
  
  augmentation:
    enabled: true
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0
    
  validation:
    interval: 1
    save_best: true
    patience: 50

# 插件配置
plugins:
  auto_discover: true
  auto_load: true
  directories:
    - "plugins"
    - "src/plugins"
  hot_reload: false
  validation:
    enabled: true
    strict: true

# 安全配置
security:
  authentication:
    required: false
    method: "token"
  api_key:
    required: false
    header_name: "X-API-Key"
  cors:
    enabled: true
    origins: ["http://localhost:3000"]
    methods: ["GET", "POST", "PUT", "DELETE"]
    headers: ["Content-Type", "Authorization"]
  rate_limiting:
    enabled: true
    requests_per_minute: 60

# 监控配置
monitoring:
  metrics:
    enabled: false
    interval: 60
  health_check:
    enabled: true
    interval: 30
  alerts:
    enabled: false

# 测试配置
testing:
  mock_external_apis: false
  test_data_dir: "test_data"
  coverage:
    enabled: false
    min_coverage: 80

# 性能配置
performance:
  max_workers: 4
  queue_size: 100
  timeout: 30
  memory_limit: "2GB"
  
# 存储配置
storage:
  type: "local"
  base_path: "data"
  temp_dir: "temp"
  cleanup_interval: 3600
  
# API配置
api:
  version: "v1"
  prefix: "/api/v1"
  docs:
    enabled: true
    path: "/docs"
  rate_limit:
    enabled: true
    requests_per_second: 10
    
# 外部服务配置
external_services:
  openai:
    enabled: false
    timeout: 30
  modelscope:
    enabled: false
    timeout: 60
  cloud_storage:
    enabled: false

# 系统配置
system:
  multiprocessing:
    enabled: true
    processes: "auto"
  memory:
    cache_size: "1GB"
    clear_cache: true
  temp:
    dir: "temp"
    cleanup: true
    max_age: 3600

# 配置管理
config:
  auto_reload: false
  validation: true
  environment_override: true
  file_watch: false